# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpsj3nd9sgp4v13a6ma/stg_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2023-04-24-r5"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-r63plbm5rmcdflrh.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "***"
  KAFKA_CONSUMER_PASSWORD: "***"
  KAFKA_CONSUMER_GROUP: "www"
  KAFKA_SOURCE_TOPIC: "order-service_orders"
  KAFKA_STG_SERVICE_ORDERS_TOPIC: "stg-service-orders"

  REDIS_HOST: "c-c9ql93v2gjens3ognt6u.rw.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "***"
  
  PG_WAREHOUSE_HOST: "rc1b-7zyeabue71hl9uqp.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "***"
  PG_WAREHOUSE_PASSWORD: "***"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
